<?php
/**
 * Created by PhpStorm.
 * User: zoe
 * Date: 2019/09/24
 * Time: 上午17:04
 * 此文件作用，彩种的配置
 */

return [
    'cqssc' => ['gameId'=>1,'name'=>'重庆时时彩','table'=>'game_cqssc','type'=>'ssc'],
    'hlsx' => ['gameId'=>2,'name'=>'欢乐生肖','table'=>'game_hlsx','type'=>'ssc'],
    'jndssc' => ['gameId'=>3,'name'=>'加拿大时时彩','table'=>'game_jndssc','type'=>'ssc'],
    'xjssc' => ['gameId'=>4,'name'=>'新疆时时彩','table'=>'game_xjssc','type'=>'ssc'],
//    'tjssc' => ['gameId'=>5,'name'=>'天津时时彩','table'=>'game_tjssc','type'=>'ssc'],
    'jsk3' => ['gameId'=>10,'name'=>'江苏快3','table'=>'game_jsk3','type'=>'k3'],
    'ahk3' => ['gameId'=>11,'name'=>'安徽快3','table'=>'game_ahk3','type'=>'k3'],
    'gxk3' => ['gameId'=>12,'name'=>'广西快3','table'=>'game_gxk3','type'=>'k3'],
    'hbk3' => ['gameId'=>13,'name'=>'湖北快3','table'=>'game_hbk3','type'=>'k3'],
    'hebeik3' => ['gameId'=>15,'name'=>'河北快3','table'=>'game_hebeik3','type'=>'k3'],
    'gsk3' => ['gameId'=>16,'name'=>'甘肃快3','table'=>'game_gsk3','type'=>'k3'],
    'gzk3' => ['gameId'=>18,'name'=>'贵州快3','table'=>'game_gzk3','type'=>'k3'],
    'gd11x5' => ['gameId'=>21,'name'=>'广东11选5','table'=>'game_gd11x5','type'=>'11x5'],
//    'fc3d' => ['gameId'=>30,'name'=>'福彩3D','table'=>'game_fc3d','type'=>''],
//    'jndhl8' => ['gameId'=>40,'name'=>'加拿大快乐八','table'=>'game_jndhl8','type'=>'kl8'],
//    'jnd28' => ['gameId'=>41,'name'=>'加拿大28','table'=>'game_jnd28','type'=>'dd'],
    'twbgc' => ['gameId'=>42,'name'=>'台湾宾果彩','table'=>'game_twbgc','type'=>'kl8'],
    'twbg28' => ['gameId'=>43,'name'=>'台湾宾果28','table'=>'game_twbg28','type'=>'dd'],
    'bjpk10' => ['gameId'=>50,'name'=>'北京赛车','table'=>'game_bjpk10','type'=>'car'],
    'xyft' => ['gameId'=>55,'name'=>'幸运飞艇','table'=>'game_xyft','type'=>'car'],
    'gdklsf' => ['gameId'=>60,'name'=>'广东快乐十分','table'=>'game_gdklsf','type'=>'nc'],
    'cqxync' => ['gameId'=>61,'name'=>'重庆幸运农场','table'=>'game_cqxync','type'=>'nc'],
    'bjkl8' => ['gameId'=>65,'name'=>'北京快乐8','table'=>'game_bjkl8','type'=>'kl8'],
    'pcdd' => ['gameId'=>66,'name'=>'PC蛋蛋','table'=>'game_pcdd','type'=>'dd'],
    'lhc' => ['gameId'=>70,'name'=>'香港六合彩','table'=>'game_lhc','type'=>'lhc'],
    'mssc' => ['gameId'=>80,'name'=>'秒速赛车','table'=>'game_mssc','type'=>'car'],
    'msssc' => ['gameId'=>81,'name'=>'秒速时时彩','table'=>'game_msssc','type'=>'ssc'],
    'msft' => ['gameId'=>82,'name'=>'秒速飞艇','table'=>'game_msft','type'=>'car'],
    'xykl8' => ['gameId'=>83,'name'=>'幸运快乐8','table'=>'game_xykl8','type'=>'kl8'],
    'xy28' => ['gameId'=>84,'name'=>'幸运28','table'=>'game_xy28','type'=>'dd'],
    'xylhc' => ['gameId'=>85,'name'=>'幸运六合彩','table'=>'game_xylhc','type'=>'lhc'],
    'msjsk3' => ['gameId'=>86,'name'=>'秒速快3','table'=>'game_msjsk3','type'=>'k3'],
    'pknn' => ['gameId'=>90,'name'=>'PK10牛牛','table'=>'game_pknn','type'=>'nn'],
    'msnn' => ['gameId'=>91,'name'=>'秒速牛牛','table'=>'game_mssc','type'=>'nn'],
    'paoma' => ['gameId'=>99,'name'=>'香港跑马','table'=>'game_paoma','type'=>'car'],
//    'txffc' => ['gameId'=>112,'name'=>'腾讯分分彩','table'=>'game_txffc','type'=>'ssc'],
    'qqffc' => ['gameId'=>113,'name'=>'QQ分分彩','table'=>'game_qqffc','type'=>'ssc'],
//    'msqxc' => ['gameId'=>114,'name'=>'秒速七星彩','table'=>'game_msqxc','type'=>''],
    'kssc' => ['gameId'=>801,'name'=>'快速赛车','table'=>'game_kssc','type'=>'car'],
    'ksft' => ['gameId'=>802,'name'=>'快速飞艇','table'=>'game_ksft','type'=>'car'],
    'ksssc' => ['gameId'=>803,'name'=>'快速时时彩','table'=>'game_ksssc','type'=>'ssc'],
    'twxyft' => ['gameId'=>804,'name'=>'台灣幸運飛艇','table'=>'game_twxyft','type'=>'car'],
    'sfsc' => ['gameId'=>901,'name'=>'三分赛车','table'=>'game_sfsc','type'=>'car'],
    'sfssc' => ['gameId'=>902,'name'=>'三分时时彩','table'=>'game_sfssc','type'=>'ssc'],
    'jslhc' => ['gameId'=>903,'name'=>'极速六合彩','table'=>'game_jslhc','type'=>'lhc'],
    'sflhc' => ['gameId'=>904,'name'=>'三分六合彩','table'=>'game_sflhc','type'=>'lhc'],
    'xylsc' => ['gameId'=>905,'name'=>'匈牙利赛车','table'=>'game_xylsc','type'=>'car'],
    'xylft' => ['gameId'=>906,'name'=>'匈牙利飞艇','table'=>'game_xylft','type'=>'car'],
    'xylssc' => ['gameId'=>907,'name'=>'匈牙利时时彩','table'=>'game_xylssc','type'=>'ssc'],
    'yfsc' => ['gameId'=>908,'name'=>'一分赛车','table'=>'game_yfsc','type'=>'car'],
    'yfssc' => ['gameId'=>909,'name'=>'一分时时彩','table'=>'game_yfssc','type'=>'ssc'],
    'yflhc' => ['gameId'=>910,'name'=>'一分六合彩','table'=>'game_yflhc','type'=>'lhc'],
    'efsc' => ['gameId'=>911,'name'=>'二分赛车','table'=>'game_efsc','type'=>'car'],
    'efssc' => ['gameId'=>912,'name'=>'二分时时彩','table'=>'game_efssc','type'=>'ssc'],
    'eflhc' => ['gameId'=>913,'name'=>'二分六合彩','table'=>'game_eflhc','type'=>'lhc'],
    'wfsc' => ['gameId'=>914,'name'=>'五分赛车','table'=>'game_wfsc','type'=>'car'],
    'wfssc' => ['gameId'=>915,'name'=>'五分时时彩','table'=>'game_wfssc','type'=>'ssc'],
    'wflhc' => ['gameId'=>916,'name'=>'五分六合彩','table'=>'game_wflhc','type'=>'lhc'],
    'shfsc' => ['gameId'=>917,'name'=>'十分赛车','table'=>'game_shfsc','type'=>'car'],
    'shfssc' => ['gameId'=>918,'name'=>'十分时时彩','table'=>'game_shfssc','type'=>'ssc'],
    'shflhc' => ['gameId'=>919,'name'=>'十分六合彩','table'=>'game_shflhc','type'=>'lhc'],
    'hkk3' => ['gameId'=>920,'name'=>'香港快三','table'=>'game_hkk3','type'=>'k3'],
    'yfk3' => ['gameId'=>921,'name'=>'一分快三','table'=>'game_yfk3','type'=>'k3'],
    'efk3' => ['gameId'=>922,'name'=>'二分快三','table'=>'game_efk3','type'=>'k3'],
    'sfk3' => ['gameId'=>923,'name'=>'三分快三','table'=>'game_sfk3','type'=>'k3'],
    'wfk3' => ['gameId'=>924,'name'=>'五分快三','table'=>'game_wfk3','type'=>'k3'],
];